[package]
name = "rattler_shell_helpers"
version = "0.1.0"
edition = "2021"
authors = ["Wolf Vollprecht <w.vollprecht@gmail.com>"]
description = "A crate to help with activation and deactivation of a conda environment"
categories = ["conda", "mamba", "package_management", "virtual_environment"]
homepage = "https://github.com/mamba-org/rattler"
repository = "https://github.com/mamba-org/rattler"
license = "BSD-3-Clause"

[dependencies]
thiserror = "1.0.30"
indexmap = "1.9.2"
serde_json = { version = "1.0.93", features = ["preserve_order"]}
tracing = "0.1.29"

[dev-dependencies]
tempdir = "0.3.7"
