[package]
name = "rattler_networking"
version = "0.26.0"
edition.workspace = true
authors = ["Wolf Vollprecht <w.vollprecht@gmail.com>"]
description = "Authenticated requests in the conda ecosystem"
categories.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true

[features]
default = ["rustls-tls", "system-integration"]
native-tls = ["reqwest/native-tls"]
rustls-tls = ["reqwest/rustls-tls"]
gcs = ["google-cloud-auth"]
s3 = ["aws-config", "aws-sdk-s3", "aws-smithy-http-client"]
system-integration = ["keyring", "netrc-rs", "dirs"]

[package.metadata.docs.rs]
features = ["gcs", "s3"]

[dependencies]
anyhow = { workspace = true }
async-once-cell = { workspace = true }
async-trait = { workspace = true }
base64 = { workspace = true }
dirs = { workspace = true, optional = true }
fs-err = { workspace = true }
google-cloud-auth = { workspace = true, optional = true }
aws-config = { workspace = true, optional = true, features = [
    "rt-tokio",
    "sso",
    "credentials-login",
    "credentials-process",
] }
aws-sdk-s3 = { workspace = true, optional = true, features = [
    "rt-tokio",
    "sigv4a",
] }
aws-smithy-http-client = { workspace = true, optional = true, features = ["rustls-ring"] }
http = { workspace = true }
itertools = { workspace = true }
keyring = { workspace = true, optional = true, features = [
    "apple-native",
    "windows-native",
    "async-secret-service",
    "async-io",
    "crypto-rust",
] }
netrc-rs = { workspace = true, optional = true }
reqwest = { workspace = true, features = ["json"] }
reqwest-middleware = { workspace = true }
retry-policies = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
rattler_config = { workspace = true, optional = true }

[target.'cfg( target_arch = "wasm32" )'.dependencies]
getrandom = { workspace = true, features = ["wasm_js"] }

[dev-dependencies]
anyhow = { workspace = true }
insta = { workspace = true, features = ["json"] }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["macros"] }
axum = { workspace = true }
reqwest-retry = { workspace = true }
sha2 = { workspace = true }
temp-env = { workspace = true }
rstest = { workspace = true }
