[package]
name = "rattler_networking"
version.workspace = true
edition.workspace = true
authors = ["Wolf Vollprecht <w.vollprecht@gmail.com>"]
description = "Authenticated requests in the conda ecosystem"
categories.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true

[features]
default = ['blocking']
native-tls = ['reqwest/native-tls']
rustls-tls = ['reqwest/rustls-tls']
blocking = ['reqwest/blocking']

[dependencies]
anyhow = "1.0.75"
dirs = "5.0.1"
keyring = "2.0.5"
lazy_static = "1.4.0"
libc = "0.2.148"
netrc-rs = "0.1.2"
reqwest = { version = "0.11.22", default-features = false}
retry-policies = { version = "0.2.0", default-features = false }
serde = "1.0.188"
serde_json = "1.0.107"
thiserror = "1.0.49"
tracing = "0.1.37"

[target.'cfg( target_arch = "wasm32" )'.dependencies]
getrandom = { version = "0.2.10", features = ["js"] }

[dev-dependencies]
anyhow = "1.0.75"
insta = { version = "1.33.0", features = ["json"] }
tempfile = "3.8.0"
