version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
    commit-message:
      prefix: chore
    groups:
      rust:
        patterns:
          - "*"
  - package-ecosystem: cargo
    directory: /py-rattler
    schedule:
      interval: weekly
    labels:
      - dependencies
    commit-message:
      prefix: chore(py)
    groups:
      rust-py-rattler:
        patterns:
          - "*"
  - package-ecosystem: cargo
    directory: /js-rattler
    schedule:
      interval: weekly
    labels:
      - dependencies
    commit-message:
      prefix: chore(js)
    groups:
      rust-js-rattler:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
    commit-message:
      prefix: chore(ci)

  - package-ecosystem: npm
    directory: /js-rattler
    schedule:
      interval: weekly
    labels:
      - dependencies
    commit-message:
      prefix: chore(js)
    groups:
      npm-dependencies:
        patterns:
          - "*"
