name: rattler-env
channels:
  - conda-forge
dependencies:
  # Needed for building rattler
  - rust =>1.65.0 
  - openssl
  - pkg-config 

  # Needed for building libsolv
  - cxx-compiler 
  - cmake
  - make