[files]
extend-exclude = [
  ".git/",
  ".pixi/",
  "*.html",
  "*.json",
  "*.svg",
  "**/*.snap",
  "**/*.txt",
  "crates/rattler_libsolv_c",
  "test-data",
  "crates/rattler_index/tests/test_index.rs",
  "js-rattler/src/PackageName.test.ts", #Â complains about valid test names in strings
]
ignore-hidden = false

[default.extend-words]
strat = "strat"
haa = "haa"
intoto = "intoto"
certifi = "certifi"
