[package]
name = "rattler_macros"
version = "1.0.9"
edition.workspace = true
authors = ["Wolf Vollprecht <w.vollprecht@gmail.com>"]
description = "A crate that provideds some procedural macros for the rattler project"
categories.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true
autotests = false

[lib]
proc-macro = true

[[test]]
name = "tests"
path = "tests/tests.rs"

[dependencies]
syn = { workspace = true }
quote = { workspace = true }

[dev-dependencies]
trybuild = { workspace = true, features = ["diff"] }
