[package]
name = "rattler_solve"
version = "0.1.0"
edition = "2021"

[dependencies]
rattler_conda_types = { version = "0.1.0", path = "../rattler_conda_types" }
libc = "0.2"
libz-sys = { version = "1.1.0", default-features = false, features = ["static"] }
anyhow = "1.0.69"
thiserror = "1.0.30"
tracing = "0.1.29"
serde = { version = "1.0.130", features = ["derive"] }
url = "2.2.2"
hex = "0.4.3"

[dev-dependencies]
insta = { version = "1.16.0", features = ["yaml"] }
serde_json = "1.0.68"
url = "2.2.2"

[build-dependencies]
anyhow = "1.0.69"
bindgen = "0.64.0"
cc = "1.0.79"
cmake = "0.1.49"

[package.metadata.cargo-udeps.ignore]
# libz-sys is required to build libsolv properly
normal = ["libz-sys"]
