[package]
name = "rattler_solve"
version = "4.2.4"
edition.workspace = true
authors = ["Bas Zalmstra <zalmstra.bas@gmail.com>"]
description = "A crate to solve conda environments"
categories.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true

[dependencies]
rattler_conda_types = { workspace = true, default-features = false }
rattler_digest = { workspace = true, default-features = false }
libc = { workspace = true, optional = true }
chrono = { workspace = true, features = ["clock"] }
humantime = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
itertools = { workspace = true }
tempfile = { workspace = true }
rattler_libsolv_c = { workspace = true, default-features = false, optional = true }
resolvo = { workspace = true, optional = true }
futures = { workspace = true, optional = true }
serde = { workspace = true, optional = true }

[dev-dependencies]
criterion = { workspace = true }
insta = { workspace = true, features = ["yaml"] }
once_cell = { workspace = true }
rattler_repodata_gateway = { path = "../rattler_repodata_gateway", default-features = false, features = [
    "sparse",
] }
rstest = { workspace = true }
serde_json = { workspace = true }
similar-asserts = { workspace = true }
url = { workspace = true }
tools = { path = "../tools" }

[features]
default = ["resolvo"]
libsolv_c = ["dep:rattler_libsolv_c", "dep:libc"]
resolvo_diagnostics = ["resolvo?/diagnostics"]
resolvo = ["dep:resolvo", "dep:futures"]

[[bench]]
name = "bench"
harness = false

[[bench]]
name = "sorting_bench"
harness = false

[package.metadata.docs.rs]
all-features = true
