[package]
name = "rattler_solve"
version.workspace = true
edition.workspace = true
authors = ["Bas Zalmstra <zalmstra.bas@gmail.com>"]
description = "A crate to solve conda environments"
categories.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true

[dependencies]
rattler_conda_types = { version = "0.11.0", path = "../rattler_conda_types" }
rattler_digest = { version = "0.11.0", path = "../rattler_digest" }
libc = { version = "0.2", optional = true }
anyhow = "1.0.75"
chrono = "0.4.31"
thiserror = "1.0.49"
tracing = "0.1.37"
itertools = "0.11.0"
serde = { version = "1.0.188", features = ["derive"] }
url = "2.4.1"
hex = "0.4.3"
tempfile = "3.8.0"
rattler_libsolv_c = { version = "0.11.0", path = "../rattler_libsolv_c", optional = true }
resolvo = { version = "0.1.0", optional = true }

[dev-dependencies]
rattler_repodata_gateway = { version = "0.11.0", path = "../rattler_repodata_gateway", default-features = false, features = ["sparse"] }
insta = { version = "1.33.0", features = ["yaml"] }
rstest = "0.18.2"
serde_json = "1.0.107"
url = "2.4.1"
similar-asserts = "1.5.0"
once_cell = "1.18.0"
criterion = "0.5.1"
test-log = { version = "0.2.12", default-features = false, features = ["trace"] }
tracing-subscriber = {version = "0.3", default-features = false, features = ["env-filter", "fmt"] }

[features]
default = ["libsolv_c"]
libsolv_c = ["rattler_libsolv_c", "libc"]

[[bench]]
name = "bench"
harness = false
