[package]
name = "rattler_solve"
version.workspace = true
edition.workspace = true
authors = ["Bas Zalmstra <zalmstra.bas@gmail.com>"]
description = "A crate to solve conda environments"
categories.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true

[dependencies]
rattler_conda_types = { version = "0.4.0", path = "../rattler_conda_types" }
rattler_digest = { version = "0.4.0", path = "../rattler_digest" }
libsolv_rs = { path = "../libsolv_rs" }
anyhow = "1.0.71"
thiserror = "1.0.40"
tracing = "0.1.37"
serde = { version = "1.0.163", features = ["derive"] }
url = "2.4.0"
hex = "0.4.3"
tempfile = "3.6.0"
cfg-if = "1.0.0"

[dev-dependencies]
rattler_repodata_gateway = { path = "../rattler_repodata_gateway", features = [
    "sparse",
] }
insta = { version = "1.29.0", features = ["yaml"] }
rstest = "0.17.0"
serde_json = "1.0.96"
url = "2.4.0"
