[package]
name = "file_url"
version = "0.1.5"
edition.workspace = true
authors = ["Bas Zalmstra <zalmstra.bas@gmail.com>"]
description = "Helper functions to work with file:// urls"
categories.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
url = { workspace = true }
percent-encoding = { workspace = true }
itertools = { workspace = true }
camino = { workspace = true }
thiserror = "1.0.61"

[dev-dependencies]
rstest = { workspace = true }
