[package]
name = "rattler_cache"
version = "0.1.5"
description = "A crate to manage the caching of data in rattler"
categories.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
readme.workspace = true

[dependencies]
anyhow.workspace = true
dirs.workspace = true
fxhash.workspace = true
itertools.workspace = true
parking_lot.workspace = true
rattler_conda_types = { version = "0.27.0", path = "../rattler_conda_types", default-features = false }
rattler_digest = { version = "1.0.0", path = "../rattler_digest", default-features = false }
rattler_networking = { version = "0.21.0", path = "../rattler_networking", default-features = false }
rattler_package_streaming = { version = "0.22.0", path = "../rattler_package_streaming", default-features = false, features = ["reqwest"] }
reqwest.workspace = true
tokio.workspace = true
tracing.workspace = true
url.workspace = true
thiserror.workspace = true
reqwest-middleware.workspace = true
digest.workspace = true

[dev-dependencies]
assert_matches.workspace = true
axum.workspace = true
bytes.workspace = true
futures.workspace = true
rstest.workspace = true
tempfile.workspace = true
tokio-stream.workspace = true
tower-http = { workspace = true, features = ["fs"] }
tools = { path = "../tools" }
