[package]
name = "rattler_pty"
version = "0.2.7"
description = "A crate to create pty"
categories.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
readme.workspace = true

[dependencies]
tokio = { workspace = true, features = ["io-util", "fs", "time"] }

[target.'cfg(unix)'.dependencies]
libc = { workspace = true }
nix = { version = "0.30.1", features = ["fs", "signal", "term", "poll"] }
signal-hook = "0.3.18"
