[package]
name = "rattler_pypi_interop"
version = "0.1.0"
categories.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
readme.workspace = true

[features]
default = ["native-tls"]
native-tls = ['reqwest/native-tls']
rustls-tls = ['reqwest/rustls-tls']

[dependencies]
bytes = { workspace = true }
ciborium = "0.2.2"
csv = "1.3.0"
data-encoding = "2.5.0"
dirs = { workspace = true }
fslock = { workspace = true }
dunce = { workspace = true }
elsa = "1.10.0"
fs4 = "0.8.2"
futures = { workspace = true }
html-escape = "0.2.13"
http = { workspace = true }
http-cache-semantics = { workspace = true, features = ["serde", "reqwest"] }
include_dir = "0.7.3"
indexmap = { workspace = true, features = ["serde"] }
itertools = { workspace = true }
miette = "7.2.0"
mime = "0.3.17"
once_cell = { workspace = true }
parking_lot = { workspace = true }
peg = "0.8.2"
pep440_rs = { version = "0.7.3" }
pep508_rs = { version = "0.9.2" }
rattler_digest = { path="../rattler_digest", version = "1.0.5", features = ["serde"] }
regex = { workspace = true }
reqwest = { workspace = true, default-features = false, features = ["json", "stream", "blocking", "rustls-tls"] }
reqwest-middleware = { workspace = true }
serde = {workspace = true }
serde_json = { workspace = true }
serde_with = {workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tl = "0.7.8"
tokio = { workspace = true, features = ["process", "rt-multi-thread"] }
tokio-util = { workspace = true, features = ["compat"] }
tracing = { workspace = true, features = ["attributes"] }
url = { workspace = true, features = ["serde"] }
zip = { workspace = true, default-features = true }
pathdiff = { workspace = true }
async_zip = { version = "0.0.16", features = ["tokio", "deflate"] }
tar = { workspace = true }
flate2 = "1.0.28"
pyproject-toml = "0.13.0"
configparser = "3.0.4"
fs-err = "2.11.0"
async_http_range_reader = "0.9.1"
which = "6.0.1"

[dev-dependencies]
anyhow = "1.0.82"
axum = "0.7.5"
criterion = "0.5"
insta = { version = "1.38.0", features = ["ron", "redactions"] }
miette = { version = "7.2.0", features = ["fancy"] }
once_cell = "1.19.0"
rstest = "0.19.0"
tokio = { version = "1.37.0", features = ["rt", "rt-multi-thread"] }
tokio-macros = { version = "2.5.0"}
tokio-test = "0.4.4"
tower-http = { version = "0.5.2", features = ["add-extension"] }
tracing-test = "0.2.4"
