[package]
name = "rattler_libsolv_rs"
version.workspace = true
edition.workspace = true
authors = ["Adolfo Ochagav√≠a <github@adolfo.ochagavia.nl>"]
description = "SAT solving library for dependency resolution"
categories.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true

[dependencies]
itertools = "0.11.0"
petgraph = "0.6.4"
tracing = "0.1.37"
elsa = "1.9.0"
bitvec = "1.0.1"
serde = { version = "1.0", features = ["derive"], optional = true }

[dev-dependencies]
insta = "1.31.0"
indexmap = "2.0.0"
proptest = "1.2.0"
tracing-test = "0.2.4"
