[package]
name = "rattler_upload"
version = "0.1.3"
edition.workspace = true
authors = ["Wolf Vollprecht <w.vollprecht@gmail.com>", "Magenta Qin <magenta2127@gmail.com>"]
description = "A crate to Upload conda packages to various channels."
categories.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true

[features]
s3 = ["rattler_networking/s3"]

[dependencies]
rattler_conda_types = { workspace = true, default-features = false }
rattler_digest = { workspace = true, default-features = false }
rattler_networking = { workspace = true, features = ["rattler_config" ]}
rattler_redaction = { workspace = true, default-features = false }
rattler_package_streaming = { workspace = true, default-features = false }
rattler_config = { workspace = true, default-features = false }
rattler_solve = { workspace = true }
ratter_progress = { workspace = true }
miette = { version = "7.6.0", features = ["fancy"] }
clap = { version = "4.5.37", features = ["derive", "env", "cargo"] }
fs-err = { workspace = true, features = ["tokio"] }
futures = "0.3.31"
indicatif = "0.18.0"
opendal = { version = "0.54.0", default-features = false, features = [
  "services-s3",
]}
reqwest-retry = "0.7.0"
tokio-util = { version = "0.7.15", features = ["codec", "compat"] }
reqwest = { version = "0.12.15", default-features = false, features = [
  "multipart",
]}
url = "2.5.4"
tracing = "0.1.41"
reqwest-middleware = { version = "0.4.2", features = ["json"] }
serde_yaml = "0.9.34"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
base64 = "0.22.1"
tempfile = "3.19.1"
thiserror = "2.0.12"
tokio = { version = "1.44.2", features = [
  "rt",
  "macros",
  "rt-multi-thread",
  "process",
] }
regex = "1.10"

[target.'cfg(not(target_os = "windows"))'.dependencies]
sha2 = { version = "0.10.8", features = ["asm"] }

[target.'cfg(target_os = "windows")'.dependencies]
sha2 = { version = "0.10.8" }
