[package]
name = "rattler_upload"
version = "0.3.5"
edition.workspace = true
authors = ["Wolf Vollprecht <w.vollprecht@gmail.com>", "Magenta Qin <magenta2127@gmail.com>"]
description = "A crate to Upload conda packages to various channels."
categories.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true

[features]
s3 = ["rattler_networking/s3", "rattler_s3"]

[dependencies]
rattler_conda_types = { workspace = true, default-features = false }
rattler_digest = { workspace = true, default-features = false }
rattler_networking = { workspace = true, features = ["rattler_config" ]}
rattler_redaction = { workspace = true, default-features = false }
rattler_package_streaming = { workspace = true, default-features = false }
rattler_config = { workspace = true, default-features = false }
rattler_solve = { workspace = true }
rattler_s3 = { workspace = true, optional = true, features = ["clap"] }
miette = { workspace = true, features = ["fancy"] }
clap = { workspace = true, features = ["env"] }
fs-err = { workspace = true, features = ["tokio"] }
futures = { workspace = true }
indicatif = { workspace = true }
opendal = { workspace = true , default-features = false, features = [
  "services-s3",
]}
reqwest-retry = { workspace = true }
tokio-util = { workspace = true, features = ["codec", "compat"] }
reqwest = { workspace = true, default-features = false, features = [
  "multipart",
]}
url = { workspace = true }
tracing = { workspace = true }
reqwest-middleware = { workspace = true, features = ["json"] }
serde_yaml = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
base64 = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = [
  "rt",
  "macros",
  "rt-multi-thread",
  "process",
] }

[target.'cfg(not(target_os = "windows"))'.dependencies]
sha2 = { workspace = true, features = ["asm"] }

[target.'cfg(target_os = "windows")'.dependencies]
sha2 = { workspace = true }
