[package]
name = "rattler_lock"
version = "0.26.14"
edition.workspace = true
authors = ["Bas Zalmstra <zalmstra.bas@gmail.com>"]
description = "Rust data types for conda lock"
categories.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true

[dependencies]
ahash = { workspace = true }
chrono = { workspace = true }
indexmap = { workspace = true, features = ["serde"] }
itertools = { workspace = true }
rattler_conda_types = { workspace = true, default-features = false }
rattler_digest = { workspace = true, default-features = false }
rattler_solve = { workspace = true, default-features = false, features = ["serde"] }
file_url = { workspace = true }
pep508_rs = { workspace = true }
pep440_rs = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_yaml = { workspace = true }
serde_with = { workspace = true, features = ["indexmap_2"] }
serde_repr = { workspace = true }
serde-value = { workspace = true }
thiserror = { workspace = true }
url = { workspace = true, features = ["serde"] }
typed-path = { workspace = true }

[dev-dependencies]
insta = { workspace = true, features = ["yaml"] }
serde_json = { workspace = true }
similar-asserts = { workspace = true }
rstest = { workspace = true }
