[package]
name = "rattler_lock"
version = "0.23.2"
edition.workspace = true
authors = ["Bas Zalmstra <zalmstra.bas@gmail.com>"]
description = "Rust data types for conda lock"
categories.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true

[dependencies]
chrono = { workspace = true }
fxhash = { workspace = true }
indexmap = { workspace = true, features = ["serde"] }
itertools = { workspace = true }
rattler_conda_types = { path = "../rattler_conda_types", version = "0.32.0", default-features = false }
rattler_digest = { path = "../rattler_digest", version = "1.1.1", default-features = false }
rattler_solve = { path = "../rattler_solve", version = "1.4.5", default-features = false, features = ["serde"] }
file_url = { path = "../file_url", version = "0.2.4" }
pep508_rs = { workspace = true }
pep440_rs = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_yaml = { workspace = true }
serde_with = { workspace = true, features = ["indexmap_2"] }
serde_repr = { workspace = true }
serde-value = { workspace = true }
thiserror = { workspace = true }
url = { workspace = true, features = ["serde"] }
typed-path = { workspace = true }

[dev-dependencies]
insta = { workspace = true, features = ["yaml"] }
serde_json = { workspace = true }
similar-asserts = { workspace = true }
rstest = { workspace = true }
