[package]
name = "tools"
version = "0.1.0"
edition = "2021"
publish = false

[features]
default = ["rustls-tls"]
native-tls = ["reqwest/native-tls"]
rustls-tls = ["reqwest/rustls-tls"]

[dependencies]
anyhow = { workspace = true }
bindgen = { workspace = true }
clap = { workspace = true, features = ["derive"] }
difference = { workspace = true }
url = { workspace = true }
fslock = { workspace = true }
dirs = { workspace = true }
thiserror = { workspace = true }
rattler_digest = { path = "../rattler_digest" }
reqwest = { workspace = true, default-features = false, features = [
  "blocking",
] }
tempfile = { workspace = true }
tokio = { workspace = true }
fs-err = { workspace = true, features = ["tokio"] }

[package.metadata.release]
# Dont publish the binary
release = false
