[package]
name = "rattler_conda_types"
version = "0.1.0"
edition = "2021"
authors = ["Bas Zalmstra <zalmstra.bas@gmail.com>"]
description = "Rust data types for common types used within the Conda ecosystem"
categories = ["conda"]
homepage = "https://github.com/mamba-org/rattler"
repository = "https://github.com/mamba-org/rattler"
license = "BSD-3-Clause"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fxhash = "0.2.1"
hex = "0.4.3"
itertools = "0.10.3"
lazy-regex = "2.3.1"
md-5 = "0.10.5"
nom = "7.1.0"
regex = "1.7.0"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.91"
serde_yaml = "0.9.17"
serde_with = "2.0.0"
serde_repr = "0.1"
sha2 = "0.10.6"
smallvec = { version = "1.10.0", features = ["serde", "const_new", "const_generics", "union"] }
strum = { version = "0.24.1", features = ["derive"] }
thiserror = "1.0.37"
tracing = "0.1.29"
url = { version = "2.2.2", features = ["serde"] }
rattler_digest = {path ="../rattler_digest", features = ["serde"]}

[dev-dependencies]
rand = "0.8.4"
insta = { version = "1.16.0", features = ["yaml", "redactions"] }
rattler_package_streaming = { path = "../rattler_package_streaming" }
tempfile = "3.3.0"
rstest = "0.16.0"
assert_matches = "1.5.0"
hex-literal = "0.3.4"
