[package]
name = "py-rattler"
version = "0.1.0"
edition = "2021"

[lib]
name = "rattler"
crate-type = ["cdylib"]

[dependencies]
rattler_conda_types = { path="../crates/rattler_conda_types", default-features = false }

pyo3 = { version = "0.19", features = ["abi3-py38", "extension-module", "multiple-pymethods"] }

thiserror = "1.0.44"

# Prevent package from thinking it's in the workspace
[workspace]
