[workspace]
members = ["pyo3-rattler"]

[workspace.package]
version = "0.3.0"
edition = "2021"
license = "BSD-3-Clause"
publish = false

[package]
name = "py-rattler"
version.workspace = true
edition.workspace = true

[lib]
name = "rattler"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
pyo3-rattler = { path = "./pyo3-rattler" }
pyo3 = { version = "0.19", features = [
    "abi3-py38",
    "extension-module",
    "multiple-pymethods",
] }

[build-dependencies]
pyo3-build-config = "0.20"
