[project]
name = "py-rattler"
version = "0.1.2"
description = "Add a short description here"
authors = [
    "Bas Zalmstra <bas@prefix.dev>",
    "Tarun Pratap Singh <pratapsinghtarun9@gmail.com>",
]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]
license = "BSD-3-Clause"

[tasks]
build = "PIP_REQUIRE_VIRTUALENV=false maturin develop"
build-release = "PIP_REQUIRE_VIRTUALENV=false maturin develop --release"
test = { cmd = "pytest --doctest-modules", depends_on = ["build"] }
fmt-python = "black ."
fmt-rust = "cargo fmt --all"
lint-python = "ruff ."
lint-rust = "cargo clippy --all"
fmt = { depends_on = ["fmt-python", "fmt-rust"] }
lint = { depends_on = ["type-check", "lint-python", "lint-rust"] }
type-check = { cmd = "mypy", depends_on = ["build"] }
docs = { cmd = "mkdocs serve" }
build-docs = { cmd = "mkdocs build" }

# checks for the CI
fmt-rust-check = "cargo fmt --all --check"
fmt-python-check = "black . --check"
fmt-check = { depends_on = ["fmt-python-check", "fmt-rust-check"] }

[dependencies]
maturin = "~=1.2.2"
pip = "~=23.2.1"
pytest = "~=7.4.0"
black = "~=23.7.0"
ruff = "~=0.0.285"
mypy = "~=1.5.1"
pytest-asyncio = "0.21.1.*"
mkdocs = "1.5.3.*"
mkdocstrings-python = "1.7.1.*"
mkdocstrings = "0.23.0.*"
mkdocs-material = "9.4.4.*"

[target.linux-64.dependencies]
patchelf = "~=0.17.2"
