[package]
name = "rattler_virtual_packages"
version.workspace = true
edition.workspace = true
authors = ["Bas Zalmstra <zalmstra.bas@gmail.com>"]
description = "Library to work with and detect Conda virtual packages"
categories.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true

[dependencies]
cfg-if = "1.0.0"
libloading = "0.8.1"
nom = "7.1.3"
once_cell = "1.18.0"
rattler_conda_types = { version = "0.16.2", path = "../rattler_conda_types" }
thiserror = "1.0.49"
tracing = "0.1.37"
serde = { version = "1.0.188", features = ["derive"] }
regex = "1.9.6"

[target.'cfg(target_os="macos")'.dependencies]
plist = "1"
