[package]
name = "rattler_package_streaming"
version.workspace = true
edition.workspace = true
authors = ["Bas Zalmstra <zalmstra.bas@gmail.com>"]
description = "Extract and stream of Conda package archives"
categories.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true

[dependencies]
thiserror = "1.0.37"
tar = { version = "0.4.38" }
bzip2 = { version = "0.4" }
zip = { version = "0.6.3" }
zstd = "0.12.1"
reqwest = { version = "0.11.13", optional = true }
tokio = { version = "1", optional = true }
tokio-util = { version = "0.7", optional = true }
futures-util = { version = "0.3.25", optional = true }
rattler_conda_types = { version = "0.1.0", path = "../rattler_conda_types" }
itertools = "0.10.5"
serde_json = "1.0.94"

[features]
tokio = ["dep:tokio", "bzip2/tokio", "tokio/fs", "tokio-util/io", "tokio-util/io-util", "reqwest?/stream", "futures-util"]
reqwest = ["reqwest/blocking"]

[dev-dependencies]
tempfile = "3.4.0"
tokio = { version = "1", features = ["rt", "macros"] }
walkdir = "2.3.2"
