[package]
name = "rattler_package_streaming"
version = "0.22.16"
edition.workspace = true
authors = ["Bas Zalmstra <zalmstra.bas@gmail.com>"]
description = "Extract and stream of Conda package archives"
categories.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true

[dependencies]
bzip2 = { workspace = true }
chrono = { workspace = true }
fs-err = { workspace = true }
futures-util = { workspace = true }
num_cpus = { workspace = true }
rattler_conda_types = { path = "../rattler_conda_types", version = "0.29.3", default-features = false }
rattler_digest = { path = "../rattler_digest", version = "1.0.3", default-features = false }
rattler_networking = { path = "../rattler_networking", version = "0.21.8", default-features = false }
rattler_redaction = { version = "0.1.4", path = "../rattler_redaction", features = ["reqwest", "reqwest-middleware"] }
reqwest = { workspace = true, features = ["stream"], optional = true }
reqwest-middleware = { workspace = true, optional = true }
serde_json = { workspace = true }
tar = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["fs"] }
tokio-util = { workspace = true, features = ["io-util"] }
tracing = { workspace = true }
url = { workspace = true }
zip = { workspace = true, features = ["deflate", "time"] }
zstd = { workspace = true, features = ["zstdmt"] }

[features]
default = ["native-tls"]
native-tls = ["rattler_networking/native-tls"]
rustls-tls = ["rattler_networking/rustls-tls"]
wasm = ["zstd/wasm"]
reqwest = ["dep:reqwest-middleware", "dep:reqwest"]

[dev-dependencies]
assert_matches = { workspace = true }
tokio = { workspace = true, features = ["rt", "macros", "rt-multi-thread"] }
tools = { path = "../tools" }
walkdir = { workspace = true }
rstest = { workspace = true }
rstest_reuse = { workspace = true }
insta = { workspace = true, features = ["yaml"] }
