[package]
name = "rattler_package_streaming"
version = "0.19.2"
edition.workspace = true
authors = ["Bas Zalmstra <zalmstra.bas@gmail.com>"]
description = "Extract and stream of Conda package archives"
categories.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true

[dependencies]
bzip2 = { workspace = true }
chrono = { workspace = true }
futures-util = { workspace = true }
itertools = { workspace = true }
num_cpus = { workspace = true }
rattler_conda_types = { path="../rattler_conda_types", version = "0.20.1", default-features = false }
rattler_digest = { path="../rattler_digest", version = "0.19.1", default-features = false }
rattler_networking = { path="../rattler_networking", version = "0.19.1", default-features = false }
reqwest = { workspace = true, features = ["stream"], optional = true }
reqwest-middleware = { workspace = true, optional = true }
serde_json = { workspace = true }
tar = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["fs"] }
tokio-util = { workspace = true, features = ["io-util"] }
url = { workspace = true }
zip = { workspace = true, features = ["deflate", "time"] }
zstd = { workspace = true, features = ["zstdmt"] }

[features]
default = ["native-tls"]
native-tls = ["rattler_networking/native-tls"]
rustls-tls = ["rattler_networking/rustls-tls"]
wasm = ["zstd/wasm"]
reqwest = ["dep:reqwest-middleware", "dep:reqwest"]

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros", "rt-multi-thread"] }
walkdir = { workspace = true }
rstest = { workspace = true }
rstest_reuse = { workspace = true }
assert_matches = { workspace = true }
