[package]
name = "rattler_package_streaming"
version = "0.23.8"
edition.workspace = true
authors = ["Bas Zalmstra <zalmstra.bas@gmail.com>"]
description = "Extract and stream of Conda package archives"
categories.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true

[dependencies]
bzip2 = { workspace = true }
chrono = { workspace = true }
fs-err = { workspace = true, features = ["tokio"] }
futures-util = { workspace = true }
num_cpus = { workspace = true }
rattler_conda_types = { workspace = true, default-features = false }
rattler_digest = { workspace = true, default-features = false }
rattler_networking = { workspace = true, default-features = false }
rattler_redaction = { workspace = true, features = [
  "reqwest",
  "reqwest-middleware",
], default-features = false }
reqwest = { workspace = true, features = ["stream"], optional = true }
reqwest-middleware = { workspace = true, optional = true }
simple_spawn_blocking = { workspace = true, features = ["tokio"] }
serde_json = { workspace = true }
tar = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = [] }
tokio-util = { workspace = true, features = ["io-util"] }
tracing = { workspace = true }
url = { workspace = true }
zip = { workspace = true, features = ["deflate", "time"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
num_cpus = { workspace = true }
tokio = { workspace = true, features = ["fs"] }
zstd = { workspace = true, features = ["zstdmt"] }

[features]
default = ["rustls-tls"]
native-tls = ["rattler_networking/native-tls", "rattler_redaction/native-tls"]
rustls-tls = ["rattler_networking/rustls-tls", "rattler_redaction/rustls-tls"]
reqwest = ["dep:reqwest-middleware", "dep:reqwest"]

[dev-dependencies]
assert_matches = { workspace = true }
tokio = { workspace = true, features = ["rt", "macros", "rt-multi-thread"] }
tools = { path = "../tools" }
walkdir = { workspace = true }
rstest = { workspace = true }
rstest_reuse = { workspace = true }
insta = { workspace = true, features = ["yaml"] }
