[package]
name = "rattler_repodata_gateway"
version = "0.23.3"
edition.workspace = true
authors = ["Bas Zalmstra <zalmstra.bas@gmail.com>"]
description = "A crate to interact with Conda repodata"
categories.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true

[dependencies]
cfg-if = { workspace = true }
fs-err = { workspace = true }
anyhow = { workspace = true }
async-compression = { workspace = true, features = ["gzip", "tokio", "bzip2", "zstd"] }
async-trait = { workspace = true, optional = true }
blake2 = { workspace = true }
bytes = { workspace = true }
cache_control = { workspace = true }
chrono = { workspace = true, features = ["std", "serde", "alloc", "clock"] }
dashmap = { workspace = true }
dirs = { workspace = true }
file_url = { workspace = true }
futures = { workspace = true }
hex = { workspace = true, features = ["serde"] }
http = { workspace = true, optional = true }
http-cache-semantics = { workspace = true, optional = true, features = ["reqwest", "serde"] }
humansize = { workspace = true }
humantime = { workspace = true }
itertools = { workspace = true, optional = true }
json-patch = { workspace = true }
self_cell = { workspace = true, optional = true }
parking_lot = { workspace = true, optional = true }
pin-project-lite = { workspace = true }
rattler_conda_types = { workspace = true, default-features = false, optional = true }
rattler_digest = { workspace = true, default-features = false, features = ["tokio", "serde"] }
rattler_networking = { workspace = true, default-features = false }
reqwest = { workspace = true, features = ["stream", "http2"] }
reqwest-middleware = { workspace = true }
rmp-serde = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_with = { workspace = true }
strum = { workspace = true }
superslice = { workspace = true, optional = true }

tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true, features = ["codec", "io"] }
tracing = { workspace = true }
url = { workspace = true, features = ["serde"] }
zstd = { workspace = true }
retry-policies = { workspace = true }
rattler_cache = { workspace = true }
rattler_redaction = { workspace = true, features = ["reqwest", "reqwest-middleware"] }

[target.'cfg(unix)'.dependencies]
libc = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true, features = ["Win32_Storage_FileSystem", "Win32_Foundation", "Win32_System_IO"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
async-fd-lock = { workspace = true }
simple_spawn_blocking = { workspace = true, features = ["tokio"] }
tokio = { workspace = true, features = ["rt", "io-util"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasmtimer = { workspace = true }

[target.'cfg(any(unix, windows))'.dependencies]
memmap2 = { workspace = true, optional = true }

[dev-dependencies]
assert_matches = { workspace = true }
axum = { workspace = true, features = ["tokio"] }
fslock = { workspace = true }
hex-literal = { workspace = true }
insta = { workspace = true, features = ["yaml"] }
rattler_conda_types = { path = "../rattler_conda_types", default-features = false }
rstest = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread"] }
tools = { path = "../tools" }
tower-http = { workspace = true, features = ["fs", "compression-gzip", "trace"] }
tracing-test = { workspace = true }

[features]
default = ['rustls-tls']
native-tls = ['reqwest/native-tls', 'reqwest/native-tls-alpn', 'rattler_networking/native-tls', 'rattler_cache/native-tls', 'rattler_redaction/native-tls']
rustls-tls = ['reqwest/rustls-tls', 'rattler_networking/rustls-tls', 'rattler_cache/rustls-tls', 'rattler_redaction/rustls-tls']
sparse = ["rattler_conda_types", "memmap2", "self_cell", "superslice", "itertools", "serde_json/raw_value"]
gateway = ["sparse", "http", "http-cache-semantics", "parking_lot", "async-trait"]

[package.metadata.docs.rs]
features = ["sparse", "gateway"]
