[package]
name = "rattler_repodata_gateway"
version.workspace = true
edition.workspace = true
authors = ["Bas Zalmstra <zalmstra.bas@gmail.com>"]
description = "A crate to interact with Conda repodata"
categories.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true

[dependencies]
async-compression = { workspace = true, features = ["gzip", "tokio", "bzip2", "zstd"] }
blake2 = { workspace = true }
cache_control = { workspace = true }
chrono = { workspace = true, features = ["std", "serde", "alloc", "clock"] }
humansize = { workspace = true }
humantime = { workspace = true }
futures = { workspace = true }
reqwest = { workspace = true, features = ["stream"] }
reqwest-middleware = { workspace = true }
tokio-util = { workspace = true, features = ["codec", "io"] }
tempfile = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
url = { workspace = true, features = ["serde"] }
tokio = { workspace = true, features = ["rt", "io-util"] }
anyhow = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
pin-project-lite = { workspace = true }
md-5 = { workspace = true }
rattler_digest = { path="../rattler_digest", version = "0.19.0", default-features = false, features = ["tokio", "serde"] }
rattler_conda_types = { path="../rattler_conda_types", version = "0.19.0", default-features = false, optional = true }
fxhash = { workspace = true, optional = true }
memmap2 = { workspace = true, optional = true }
ouroboros = { workspace = true, optional = true }
serde_with = { workspace = true }
superslice = { workspace = true, optional = true }
itertools = { workspace = true, optional = true }
json-patch = { workspace = true }
hex = { workspace = true, features = ["serde"] }
rattler_networking = { path="../rattler_networking", version = "0.19.0", default-features = false }

[target.'cfg(unix)'.dependencies]
libc = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true, features = ["Win32_Storage_FileSystem", "Win32_Foundation", "Win32_System_IO"] }

[dev-dependencies]
assert_matches = { workspace = true }
axum = { workspace = true, features = ["tokio"] }
hex-literal = { workspace = true }
insta = { workspace = true, features = ["yaml"] }
rstest = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tower-http = { workspace = true, features = ["fs", "compression-gzip", "trace"] }
tracing-test = { workspace = true }

[features]
default = ['native-tls']
native-tls = ['reqwest/native-tls']
rustls-tls = ['reqwest/rustls-tls']
sparse = ["rattler_conda_types", "memmap2", "ouroboros", "superslice", "itertools", "serde_json/raw_value"]
