[package]
name = "rattler_shell"
version.workspace = true
edition.workspace = true
authors = ["Wolf Vollprecht <w.vollprecht@gmail.com>"]
description = "A crate to help with activation and deactivation of a conda environment"
categories = ["conda", "mamba", "package_management", "virtual_environment"]
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true

[dependencies]
enum_dispatch = "0.3.12"
indexmap = "2.0.2"
itertools = "0.11.0"
rattler_conda_types = { version = "0.14.0", path = "../rattler_conda_types" }
serde_json = { version = "1.0.107", features = ["preserve_order"] }
shlex = "1.2.0"
sysinfo = { version = "0.29.10", optional = true }
tempfile = "3.8.0"
thiserror = "1.0.49"
tracing = "0.1.37"

[dev-dependencies]
insta = { version = "1.33.0", features = ["yaml"] }
tempdir = "0.3.7"
