[package]
name = "rattler_shell"
version.workspace = true
edition.workspace = true
authors = ["Wolf Vollprecht <w.vollprecht@gmail.com>"]
description = "A crate to help with activation and deactivation of a conda environment"
categories = ["conda", "mamba", "package_management", "virtual_environment"]
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true

[dependencies]
enum_dispatch = "0.3.11"
indexmap = "1.9.3"
itertools = "0.10.5"
rattler_conda_types = { version = "0.4.0", path = "../rattler_conda_types" }
serde_json = { version = "1.0.96", features = ["preserve_order"] }
thiserror = "1.0.40"
tracing = "0.1.37"
sysinfo = { version = "0.29.2", optional = true }

[dev-dependencies]
tempdir = "0.3.7"
insta = "1.29.0"
