[package]
name = "rattler_shell"
version.workspace = true
edition.workspace = true
authors = ["Wolf Vollprecht <w.vollprecht@gmail.com>"]
description = "A crate to help with activation and deactivation of a conda environment"
categories = ["conda", "mamba", "package_management", "virtual_environment"]
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true

[dependencies]
thiserror = "1.0.30"
indexmap = "1.9.2"
serde_json = { version = "1.0.93", features = ["preserve_order"]}
tracing = "0.1.29"

[dev-dependencies]
tempdir = "0.3.7"
insta = "1.28.0"
