[package]
name = "rattler_shell"
version = "0.20.3"
edition.workspace = true
authors = ["Wolf Vollprecht <w.vollprecht@gmail.com>"]
description = "A crate to help with activation and deactivation of a conda environment"
categories = ["conda", "mamba", "package_management", "virtual_environment"]
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true

[dependencies]
enum_dispatch = { workspace = true }
indexmap = { workspace = true }
itertools = { workspace = true }
rattler_conda_types = { path="../rattler_conda_types", version = "0.23.0", default-features = false }
serde_json = { workspace = true, features = ["preserve_order"] }
shlex = { workspace = true }
sysinfo = { workspace = true, optional = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
insta = { workspace = true, features = ["yaml"] }
tempdir = { workspace = true }
