name: JS bindings CI

on:
  push:
    branches: [main]
  pull_request:
    paths:
      # When we change pyproject.toml, we want to ensure that the maturin builds still work
      - test-data/**
      - crates/**
      - Cargo.*

      # When something in the bindings themselves changes
      - "js-rattler/**/*"

      # Or when this workflow changes
      - ".github/workflows/js-bindings.yml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  RUST_LOG: info
  RUST_BACKTRACE: 1
  RUSTFLAGS: "-D warnings --cfg getrandom_backend=\"wasm_js\""

jobs:
  format_lint_test:
    name: Format, Lint and Test the JS bindings
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["20.x"]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy, rustfmt
          target: wasm32-unknown-unknown
          cache-workspaces: js-rattler -> target

      - name: Run rustfmt
        uses: actions-rust-lang/rustfmt@v1
        with:
          manifest-path: js-rattler/Cargo.toml

      - name: Run clippy
        run: cargo clippy --all-targets --locked
        working-directory: js-rattler

      - run: npm ci
        working-directory: js-rattler
      - run: npm run fmt:check
        working-directory: js-rattler
      - run: npm run build
        working-directory: js-rattler
      - run: npm test
        working-directory: js-rattler

      # some e2e test to make sure our build works
      - run: |
          set -euxo pipefail

          node ./e2e/main.cjs
          node ./e2e/main.mjs
        working-directory: js-rattler
