name: Rust Release

permissions:
  pull-requests: write
  contents: write

on:
  push:
    branches:
      - main

jobs:
  release-plz:
    name: Release-plz
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.RELEASE_PLZ_TOKEN }}
          lfs: false
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@f9f65f52341ba3c1d5e1901c77dc7a9e58186191 # stable

      - name: Disable LFS globally
        # We really don't want to checkout / clone / fetch any LFS files anymore
        run: |
          # Remove LFS first
          git lfs uninstall
          sudo apt remove -y git-lfs

          # Clean any LFS remnants
          rm -rf .git/lfs
          rm -rf ~/.git-lfs

          # Verify configs are gone
          git config --global --list

      - name: Run release-plz
        uses: MarcoIeni/release-plz-action@bbd1afc9813d25602e002b29e96e0aacebab1160 # v0.5
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PLZ_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
