name: Rust Release

permissions:
  pull-requests: write
  contents: write

on:
  push:
    branches:
      - main

jobs:
  release-plz:
    name: Release-plz
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.RELEASE_PLZ_TOKEN }}
          lfs: false
      - uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6 # v2.7.8
      - name: Install Rust toolchain
        run: rustup show

      - name: Disable LFS globally
        # We really don't want to checkout / clone / fetch any LFS files anymore
        run: |
          # Remove LFS first
          git lfs uninstall
          sudo apt remove -y git-lfs

          # Clean any LFS remnants
          rm -rf .git/lfs
          rm -rf ~/.git-lfs

          # Verify configs are gone
          git config --global --list

      - name: Run release-plz
        uses: MarcoIeni/release-plz-action@8724d33cd97b8295051102e2e19ca592962238f5 # v0.5
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PLZ_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
